### ISSUE TITLE
Trying to close a block 116 that does not match the last confirmed block 116

### ISSUE THREAD

**Issue by mcsherrylabs** [mcsherrylabs/sss.openstar#4]
[ERROR] [07/15/2016 11:54:18.436] [asado-network-node-akka.actor.default-dispatcher-11] [akka://asado-network-node/user/$g] requirement failed: Trying to close a block 116 that does not match the last confirmed block 116
java.lang.IllegalArgumentException: requirement failed: Trying to close a block 116 that does not match the last confirmed block 116
    at scala.Predef$.require(Predef.scala:224)
    at sss.asado.block.BlockChainActor$$anonfun$sss$asado$block$BlockChainActor$$waiting$1.applyOrElse(BlockChainActor.scala:178)
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
    at sss.asado.block.BlockChainActor.aroundReceive(BlockChainActor.scala:61)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
    at akka.actor.ActorCell.invoke(ActorCell.scala:495)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
    at akka.dispatch.Mailbox.run(Mailbox.scala:224)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[WARN] [07/15/2016 11:54:18.438] [asado-network-node-akka.actor.default-dispatcher-11] [akka://asado-network-node/user/$g] BlockChain actor is down!
[INFO] [07/15/2016 11:54:18.439] [asado-network-node-akka.actor.default-dispatcher-11] [akka://asado-network-node/user/$g] BlockChain actor has started...

**Comment by mcsherrylabs** [comment]
Removing partial close may fix this. Check back.
